baseurl = "https://leemacaulay.gitlab.io/vonc-club/"
title = "V.O.N.C - Extreme"
author = ""
copyright = "&copy; 2003"
canonifyurls = true
paginate = 5

googleAnalytics = ""

theme = "strange-case"

[params]
	colorScheme = "scheme-custom"
	DateFormat = "2 Jan 2006"
	description = "your challenge awaits"
	sidebarDescription = "This is my blog about content"
	sidebarFreeText = ""
	piwikSiteID = ""
	piwikURL = ""

[[menu.main]]
	name = "Game Rules"
	url = "/gamerules"

[[menu.main]]
	name = "Game Statistics"
	url = "/stat"

[[menu.main]]
  name = "Scoring Table"
  url = "/table"

[[menu.main]]
  name = "Home"
  url = "/"

[[menu.main]]
  name = "The War"
  url = "/war"
